# fly.toml app configuration file generated for refly-al-agent-lingering-leaf-1143 on 2024-12-31T06:12:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'refly-ai-agent'
primary_region = 'nigeria'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
